#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.1.1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.UPower.conf 0.99.9-2\~ -- "$@"
# End automatically added section
